services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Redirection HTTP -> HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # Let's Encrypt (HTTP-01)
      - --certificatesresolvers.le.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      # Debug utile au début
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/acme.json:/letsencrypt/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.docker.network=app_src_proxy
      - traefik.http.services.app.loadbalancer.server.port=3000
      # Apex (canonique)
      - traefik.http.routers.app.rule=Host(`bde-ensar.fr`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=le
      # www -> apex (301)
      - traefik.http.routers.app-www.rule=Host(`www.bde-ensar.fr`)
      - traefik.http.routers.app-www.entrypoints=websecure
      - traefik.http.routers.app-www.tls=true
      - traefik.http.routers.app-www.tls.certresolver=le
      - traefik.http.routers.app-www.middlewares=redirect-to-apex
      - traefik.http.middlewares.redirect-to-apex.redirectregex.regex=^https?://www\.bde-ensar\.fr(.*)
      - traefik.http.middlewares.redirect-to-apex.redirectregex.replacement=https://bde-ensar.fr$$1
      - traefik.http.middlewares.redirect-to-apex.redirectregex.permanent=true
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:3000/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - proxy
      - internal
    environment:
    - PORT=3000
    - HOSTNAME=0.0.0.0
    volumes:
      - uploads:/app/public/upload

  db:
    image: mariadb:11.4
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-bde_prod}
      MARIADB_USER: ${MARIADB_USER:-bde_prod}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p\"$${MARIADB_ROOT_PASSWORD}\" --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 60s
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - internal

volumes:
  dbdata:
  uploads:

networks:
  proxy:
    driver: bridge
  internal:
    driver: bridge
