version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Let's Encrypt (HTTP-01)
      - --certificatesresolvers.le.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/acme.json:/letsencrypt/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

  # EXEMPLE: ton app Next.js "web" (rappel)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      # HTTPS
      - traefik.http.routers.app.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls.certresolver=le
      - traefik.http.services.app.loadbalancer.server.port=3000
      - traefik.http.routers.app.middlewares=security-headers@file
      # HTTP -> HTTPS
      - traefik.http.routers.app-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.app-http.entrypoints=web
      - traefik.http.routers.app-http.middlewares=redirect-to-https@file
    networks:
      - proxy
      - internal
    volumes:
      - uploads:/app/Upload

  db:
    image: mariadb:11.4
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-bde_prod}
      MARIADB_USER: ${MARIADB_USER:-bde_prod}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      # Utilise mariadb-admin + QUOTES + $$ pour le mot de passe
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p\"$${MARIADB_ROOT_PASSWORD}\" --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 60s   # laisse le temps à l'init la 1ère fois
    networks:
      - internal

volumes:
  dbdata:
  uploads:  

networks:
  proxy:
    driver: bridge
  internal:
    driver: bridge
